# Generated by Django 4.1.6 on 2023-02-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=10)),
                ('row', models.IntegerField()),
                ('col', models.IntegerField()),
                ('level', models.IntegerField()),
            ],
        ),
    ]
