# Generated by Django 4.1.6 on 2023-02-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordle', '0002_user_best_tries_6_alter_user_best_tries_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='percentage_of_win',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
