# Generated by Django 4.1.6 on 2023-02-28 16:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordle', '0004_alter_user_best_try'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='average_duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
